### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by mencagli** [ShuhaoZhangTony/briskstream#8]
Hi Tony,

I am working again with BriskStream and since I have an old version, I tried to download the new stable branch and to restart working on it since it is actively maintained by you.

I tried to compile the project running
mvn validate
mvn install -DskipTests

as in your guide. I receive an error during the compilation of the project "affinity". The error is the following:

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (build-native) on project affinity: Command execution failed.: Cannot run program "/home/mencagli/BriskStream_New/affinity/src/main/c/Makefile" (in directory "/home/mencagli/BriskStream_New/affinity/src/main/c"): error=13, Permission denied -> [Help 1]

it seems that the Makefile does not have the execution permission that is right since it is not a binary but just a Makefile. Do you have any guess on how to solve this issue and compile BriskStream correctly?

Thanks!

**Comment by cyrus-and** [comment]
It's enough to make it executable since it has a shebang (`#!/usr/bin/make -f`):

```
chmod +x affinity/src/main/c/Makefile
```

**Comment by cyrus-and** [comment]
This needs to be fixed though...

**Comment by ShuhaoZhangTony** [comment]
Yes, need to change the execute mode.  :)
